apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "AEGIS.namespace" . }}
  labels:
    {{- include "AEGIS.labels" . | nindent 4 }}
    AEGIS.io/environment: {{ .Values.global.environment }}
